### ISSUE TITLE
set-role-variables - Condition is wrong evaluated for ansible_distribution_version

### ISSUE THREAD

**Issue by colandre** [abednarik/ansible-role-mysqld-exporter#3]
Hello,

I think that in file set-role-variables.yml there would be a problem with the "when" condition.

```
when: ansible_distribution == "CentOS" and ansible_distribution_version|int >= 7
```

In my case, the fact ansible_distribution_version is evaluated with 7.2.1511 and passing it through the |int function, it returns "0", due to multiple dots separator.

How to replicate:
```
ansible -vvv -i localhost, -c local -m debug -a "var={{ '7.2.1511' | int }}" all
```

I think that a better variable that can be used for the when condition could be: ansible_distribution_major_version

(The result of this issue is for me the installation of the mysql_exporter deamon as service in /etc/init.d instead of place the service in /etc/systemd/system folder. I'm running CentOS v7.2.1511)

Thanks

**Comment by abednarik** [comment]
Thanks for bringing this issue and a possible solution. Will work in this tomorrow to find a fix.

Cheers

**Comment by abednarik** [comment]
HI @colandre 

 I just pushed the fix as you suggested, but something is wrong here. I will need to take a deeper look once I have some free time.

Thanks.

**Comment by abednarik** [comment]
Hi @colandre 

 Can you try this branch https://github.com/abednarik/ansible-role-mysqld-exporter/pull/4/ The issue here is that systemd and docker doesn't play well together. IF we want to test in inside docker the systemd unit, I need to change Docker images with others that support systemd.

Thanks.

**Comment by colandre** [comment]
Thank you for your time @abednarik. It works.
